### ISSUE TITLE
缺少图片文件

### ISSUE THREAD

**Issue by ice-b-114** [Yuri-YuzuChaN/maimaiDX#106]
使用命令“13+完成表”
```
[2023-08-11 11:46:29,205 maimaiDX] ERROR: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\HoshinoBot\\hoshino\\modules\\maimaiDX\\static\\mai\\rating\\13+.png'
Traceback (most recent call last):
  File "C:\Users\Administrator\HoshinoBot\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 656, in rating_table_pf
    img = await rating_table_draw({'qq': qqid}, args)
  File "C:\Users\Administrator\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music_info.py", line 357, in rating_table_draw
    im = Image.open(bg).convert('RGBA')
  File "C:\Users\Administrator\HoshinoBot\lib\site-packages\PIL\Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\HoshinoBot\\hoshino\\modules\\maimaiDX\\static\\mai\\rating\\13+.png'
```
确认已重新下载静态文件，但压缩包里并没有对应的图片，大佬看看是否上传错了

**Comment by Yuri-YuzuChaN** [comment]
这个要你自己私聊bot `更新定数表` 指令来生成定数表，因为每个版本都会有新歌，不会次次都添加定数表在静态资源内

**Comment by Yuri-YuzuChaN** [comment]
可以详细看下README的重要更新
