### ISSUE TITLE
ubuntu系统下使用中的一些问题

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Yuri-YuzuChaN/maimaiDX#107]
1.无法手动更新定数表
日志如下
```Python
[2023-08-11 17:47:57,152 maimaiDX] ERROR: Traceback (most recent call last):
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimaidx_music_info.py", line 310, in update_rating_table
    cover_bg = diff[music.lv]
TypeError: list indices must be integers or slices, not str
```
2.资源文件名大小写不一致导致无法输出b50图片
日志如下
```Python
[2023-08-11 17:49:39,588 maimaiDX] ERROR: <class 'FileNotFoundError'> occured when best_50 handling message -834436405.
2023-08-11 17:49:39 ERROR <class 'FileNotFoundError'> occured when best_50 handling message -834436405.
[2023-08-11 17:49:39,606 maimaiDX] ERROR: [Errno 2] No such file or directory: '/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/static/mai/pic/UI_MSS_MBase_Icon_FCp.png'
Traceback (most recent call last):
  File "/home/yuyue/HoshinoBot/hoshino/msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/maimai.py", line 550, in best_50
    await bot.send(ev, await generate(payload), at_sender=True)
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimai_best_50.py", line 331, in generate
    pic = await draw_best.draw()
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimai_best_50.py", line 197, in draw
    await self.whiledraw(self.sdBest, True)
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimai_best_50.py", line 119, in whiledraw
    fc = Image.open(os.path.join(maimaidir, f'UI_MSS_MBase_Icon_{fcl[info.fc]}.png')).resize((45, 45))
  File "/home/yuyue/.cache/pypoetry/virtualenvs/hoshinobot-YwPoqgTR-py3.8/lib/python3.8/site-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/static/mai/pic/UI_MSS_MBase_Icon_FCp.png'
```

**Comment by Yuri-YuzuChaN** [comment]
1. 暂时不知道什么原因，不知道你那边 `diff` 有没有循环创建图片
https://github.com/Yuri-YuzuChaN/maimaiDX/blob/fff77f56c5d6267420aed534d46a93917c0e9ce5/libraries/maimaidx_music_info.py#L263-L265
2. 我这边上传的文件可能传错了，传成小写的了

**Comment by Yuri-YuzuChaN** [comment]
已修复问题一 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/32863fc87db56bdcb8d06124e28de91964e24e3b
