### ISSUE TITLE
你的别名api貌似炸了，和连不上api下无法添加本地别名

### ISSUE THREAD

**Issue by Xian0Grem** [Yuri-YuzuChaN/maimaiDX#133]
[2023-12-06 15:18:07,516 nonebot] INFO: Self: 2329289433, Message -2013298010 from 2640036416@[群:640524517]: '添加本地别名 11408 自杀列车'
[2023-12-06 15:18:07,517 maimaiDX] INFO: Message -2013298010 triggered apply_local_alias.
[2023-12-06 15:18:09,939 maimaiDX] ERROR: <class 'hoshino.modules.maimaiDX.libraries.maimaidx_error.UnknownError'> occured when apply_local_alias handling message -2013298010.
[2023-12-06 15:18:09,939 maimaiDX] ERROR:
Traceback (most recent call last):
  File "F:\HoshinoBot\HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "F:\HoshinoBot\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 326, in apply_local_alias
    server_exist = await maiApi.get_songs(id)
  File "F:\HoshinoBot\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_api_data.py", line 113, in get_songs
    return await self._request('GET', self.MaiAliasAPI + '/getsongsalias', params={'id': id})
  File "F:\HoshinoBot\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_api_data.py", line 49, in _request
    raise UnknownError
hoshino.modules.maimaiDX.libraries.maimaidx_error.UnknownError
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001CFDDE0B910>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001CFDE208EE0>, 886754.64)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001CFDDE0BA00>
[2023-12-06 15:18:09,942 nonebot] INFO: Message -2013298010 is ignored: Handled by Hoshino

**Comment by Xian0Grem** [comment]
> api一切正常

那能帮我看看我的报错吗
![9cb12db66b3034dcbb263b9fde949ecd](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/65611818/4b183911-e77d-45e8-be42-79a11559e686)

**Comment by Yuri-YuzuChaN** [comment]
看了下我这证书又出问题了，你现在再试试，应该可以了

**Comment by Xian0Grem** [comment]
> 看了下我这证书又出问题了，你现在再试试，应该可以了

要不写个可以在无法连接api的情况下添加本地别名(

**Comment by Yuri-YuzuChaN** [comment]
后续换服务器了，不会再出现这种问题，现在先用着吧

**Comment by Xian0Grem** [comment]
> 后续换服务器了，不会再出现这种问题，现在先用着吧

嘟嘟，好吧
