### ISSUE TITLE
静态文件需要更新，否则查询新版本歌曲会报错提示找不到buddies代版本logo

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Yuri-YuzuChaN/maimaiDX#144]
![image](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/86163024/329f7e29-7047-40a4-99e9-eb5f65ddb86e)

报错如下
```
[2024-06-06 12:57:28,578 nonebot] INFO: Self: 25*****89, Message 1012001431 from 245*****73@[群:658967247]: '查歌 VeRForTe αRtE:VEiN'
2024-06-06 12:57:28 INFO Self: 25*****89, Message 1012001431 from 245*****73@[群:6******47]: '查歌 VeRForTe αRtE:VEiN'
[2024-06-06 12:57:28,580 maimaiDX] INFO: Message 1012001431 triggered search_song.
2024-06-06 12:57:28 INFO Message 1012001431 triggered search_song.
2024-06-06 12:57:28 WARNING Executing <Task pending name='Task-28' coro=<handle_message() running at /home/yuyue/HoshinoBot/hoshino/msghandler.py:23> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.8/asyncio/tasks.py:902, <TaskWakeupMethWrapper object at 0x70fbb5a03a60>()] created at /usr/lib/python3.8/asyncio/base_events.py:422> cb=[gather.<locals>._done_callback() at /usr/lib/python3.8/asyncio/tasks.py:769] created at /usr/lib/python3.8/asyncio/tasks.py:824> took 0.365 seconds
[2024-06-06 12:57:29,092 maimaiDX] ERROR: <class 'FileNotFoundError'> occured when search_song handling message 1012001431.
2024-06-06 12:57:29 ERROR <class 'FileNotFoundError'> occured when search_song handling message 1012001431.
[2024-06-06 12:57:29,092 maimaiDX] ERROR: [Errno 2] No such file or directory: '/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/static/mai/pic/maimai でらっくす BUDDiES.png'
Traceback (most recent call last):
  File "/home/yuyue/HoshinoBot/hoshino/msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/maimai.py", line 219, in search_song
    msg = await new_draw_music_info(result.random())
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimaidx_music_info.py", line 228, in new_draw_music_info
    im.alpha_composite(Image.open(maimaidir / f'{music.basic_info.version}.png').resize((250, 120)), (1340, 590))
  File "/home/yuyue/.cache/pypoetry/virtualenvs/hoshinobot-YwPoqgTR-py3.8/lib/python3.8/site-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/static/mai/pic/maimai でらっくす BUDDiES.png'
2024-06-06 12:57:29 ERROR [Errno 2] No such file or directory: '/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/static/mai/pic/maimai でらっくす BUDDiES.png'
Traceback (most recent call last):
  File "/home/yuyue/HoshinoBot/hoshino/msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/maimai.py", line 219, in search_song
    msg = await new_draw_music_info(result.random())
  File "/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimaidx_music_info.py", line 228, in new_draw_music_info
    im.alpha_composite(Image.open(maimaidir / f'{music.basic_info.version}.png').resize((250, 120)), (1340, 590))
  File "/home/yuyue/.cache/pypoetry/virtualenvs/hoshinobot-YwPoqgTR-py3.8/lib/python3.8/site-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/yuyue/HoshinoBot/hoshino/modules/maimaiDX/static/mai/pic/maimai でらっくす BUDDiES.png'
[2024-06-06 12:57:29,095 nonebot] INFO: Message 1012001431 is ignored: Handled by Hoshino
2024-06-06 12:57:29 INFO Message 1012001431 is ignored: Handled by Hoshino
```

**Comment by Yuri-YuzuChaN** [comment]
新版本变动较大，还需要一点时间做测试

**Comment by Yuri-YuzuChaN** [comment]
已更新 2024
