### ISSUE TITLE
关于b40和b50和添加别称无法正常使用的问题

### ISSUE THREAD

**Issue by 1306197556** [Yuri-YuzuChaN/maimaiDX#21]
其他的功能都能正常使用

**Comment by Yuri-YuzuChaN** [comment]
看下log

**Comment by 1306197556** [comment]
[2022-01-21 23:08:57,588 maimaiDX] INFO: Message 44659429 triggered best_40.
[2022-01-21 23:08:57,588 maimaiDX] ERROR: <class 'AttributeError'> occured when best_40 handling message 44659429.
[2022-01-21 23:08:57,589 maimaiDX] ERROR: 'Event' object has no attribute 'prefix'
Traceback (most recent call last):
  File "D:\haru-bot-setup-master\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "D:\haru-bot-setup-master\hoshino\modules\maimaiDX\maimai.py", line 283, in best_40
    if ev.prefix.lower() == 'b50':
AttributeError: 'Event' object has no attribute 'prefix'

**Comment by 1306197556** [comment]
nonebot报的这个

**Comment by Yuri-YuzuChaN** [comment]
你的nonebot和aiocqhttp依赖的版本是不是最新的

**Comment by 1306197556** [comment]
更新后b40可以使用了，但是添加别称还是无法使用

**Comment by Yuri-YuzuChaN** [comment]
已修复该问题，[bug部分](https://github.com/Yuri-YuzuChaN/maimaiDX/commit/c72f0e64df0fa406262f1fd2e9af44aa6eb54580)
