### ISSUE TITLE
柚子柚子！查询b40/b50的时候会遇到prefix的属性错误QAQ，请问应该怎么解决x，辛苦柚子了www

### ISSUE THREAD

**Issue by luoyeye001** [Yuri-YuzuChaN/maimaiDX#26]
[2022-04-10 08:08:11,187 maimaiDX] ERROR: <class 'AttributeError'> occured when best_40 handling message 1015516085.
[2022-04-10 08:08:11,187 maimaiDX] ERROR: 'Event' object has no attribute 'prefix'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot-2.0-RIP\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot-2.0-RIP\hoshino\modules\maimaiDX\maimai.py", line 303, in best_40
    if ev.prefix.lower() == 'b50':
AttributeError: 'Event' object has no attribute 'prefix'

**Comment by Yuri-YuzuChaN** [comment]
![Uploading Screenshot_2022-04-10-11-22-20-598-edit_com.qihoo.contents.jpg…]()

**Comment by Yuri-YuzuChaN** [comment]
![Screenshot_2022-04-10-11-22-20-598-edit_com qihoo contents](https://user-images.githubusercontent.com/65105396/162600064-e7c794b0-df8e-40d4-82e7-63c519ae5a96.jpg)
