### ISSUE TITLE
Cannot connect to host www.diving-fish.com:443 ssl:default [指定的网络名不再可用。]

### ISSUE THREAD

**Issue by Naexen** [Yuri-YuzuChaN/maimaiDX#28]
PS D:\Apps\HoshinoBot> py -3.8 run.py
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
[2022-04-21 17:35:46,604 config] WARNING: Not found config of "botmanage"
[2022-04-21 17:35:46,604 config] WARNING: Not found config of "dice"
[2022-04-21 17:35:46,604 config] INFO: Succeeded to load config of "groupmaster"
[2022-04-21 17:35:46,604 config] WARNING: Not found config of "maimaiDX"
[2022-04-21 17:35:47,620 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.alert"
[2022-04-21 17:35:47,620 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.billing"
[2022-04-21 17:35:47,635 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.broadcast"
[2022-04-21 17:35:47,635 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.data_cleaner"
[2022-04-21 17:35:47,651 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.feedback"
[2022-04-21 17:35:47,651 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.get_cqcode"
[2022-04-21 17:35:47,651 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_invite"
[2022-04-21 17:35:47,651 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_leave"
[2022-04-21 17:35:47,651 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.help"
[2022-04-21 17:35:47,666 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.ls"
[2022-04-21 17:35:47,666 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.service_manage"
[2022-04-21 17:35:47,666 nonebot] INFO: Succeeded to import "hoshino.modules.dice.dice"
[2022-04-21 17:35:47,791 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.antiqks"
[2022-04-21 17:35:47,791 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_abuse"
[2022-04-21 17:35:47,791 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_asoul"
[2022-04-21 17:35:47,791 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_holo"
[2022-04-21 17:35:47,916 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_lex"
[2022-04-21 17:35:47,916 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_msg_recall"
[2022-04-21 17:35:47,916 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.chat"
[2022-04-21 17:35:47,916 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.group_notice"
[2022-04-21 17:35:47,932 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.join_approve"
[2022-04-21 17:35:47,932 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.random_repeater"
[2022-04-21 17:35:47,932 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.sleeping_set"
[2022-04-21 17:35:47,963 nonebot] INFO: Succeeded to import "hoshino.modules.maimaiDX.maimai"
[2022-04-21 17:35:47,963 nonebot] INFO: Running on 0.0.0.0:8088
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://0.0.0.0:8088 (CTRL + C to quit)
[2022-04-21 17:35:47,963 nonebot] INFO: Scheduler started
Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 457, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 280, in _loop_reading
    data = fut.result()
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 461, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\asgi.py", line 228, in __call__
    await self.app.startup()
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2149, in startup
    await func()
  File "D:\Apps\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 86, in get_music
    await mai.get_music()
  File "D:\Apps\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 238, in get_music
    self.total_list = await get_music_list()
  File "D:\Apps\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 205, in get_music_list
    async with aiohttp.request("GET", 'https://www.diving-fish.com/api/maimaidxprober/music_data') as obj_data:
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 1186, in __aenter__
    self._resp = await self._coro
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.diving-fish.com:443 ssl:default [指定的网络名不再可用。]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 8, in <module>
    bot.run(use_reloader=False, loop=asyncio.get_event_loop())
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\__init__.py", line 61, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 222, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1671, in run
    loop.run_until_complete(task)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\__init__.py", line 41, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\run.py", line 85, in worker_serve
    raise exception
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\lifespan.py", line 32, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\utils.py", line 247, in invoke_asgi
    await app(scope, receive, send)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2117, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 2140, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\asgi.py", line 230, in __call__
    await send({"type": "lifespan.startup.failed", "message": str(error)})
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\lifespan.py", line 84, in asgi_send
    raise LifespanFailureError("startup", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. 'Cannot connect to host www.diving-fish.com:443 ssl:default [指定的网络名不再可用。]'

**Comment by Naexen** [comment]
自行启用科学上网后解决。
ps：新版本添加的retrying依赖需要手动安装 建议再塞个requirements进去

**Comment by Naexen** [comment]
没有不挂梯子也能启动的方法吗（

**Comment by Naexen** [comment]
自测关闭梯子的情况下可以正常访问水鱼佬的站点，但是bot仍然无法正常启用

**Comment by Naexen** [comment]
自行尝试访问相关需求站点 基本需要连续刷新数次才能正常访问UwU
不知道我有没有自行调整的方法？多加几次retry有没有可能改善这种情况？而不是一次连接失败就关闭整个框架

**Comment by Naexen** [comment]
发现问题所在了草 nslookup一遍发现是df的站自动解析了v6但是我本机dns不知道为啥没正确跳转
