### ISSUE TITLE
b40指令报错

### ISSUE THREAD

**Issue by RisaInasaka** [Yuri-YuzuChaN/maimaiDX#29]
系统环境`ubuntu 22.04 lts w/ python 3.10.4 (system)`
已手动`pip3 -U`升级nonebot和aiocqhttp

Note: `pyenv 3.9.12`环境下正常运行

```
[2022-04-22 15:33:19,625 maimaiDX] INFO: Message -421822641 triggered best_40.
[2022-04-22 15:33:20,750 maimaiDX] ERROR: <class 'TypeError'> occured when best_40 handling message -421822641.
[2022-04-22 15:33:20,751 maimaiDX] ERROR: 'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/risa/maimaidx/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/home/risa/maimaidx/HoshinoBot/hoshino/modules/maimaiDX/maimai.py", line 397, in best_40
    data = await generate(payload)
  File "/home/risa/maimaidx/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimai_best_40.py", line 533, in generate
    pic = await draw_best.draw()
  File "/home/risa/maimaidx/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimai_best_40.py", line 449, in draw
    self._drawBestList(self.img, self.sdBest, self.dxBest)
  File "/home/risa/maimaidx/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimai_best_40.py", line 296, in _drawBestList
    temp = temp.point(lambda p: p * 0.72)
  File "/home/risa/.local/lib/python3.10/site-packages/PIL/Image.py", line 1723, in point
    return self._new(self.im.point(lut, mode))
TypeError: 'float' object cannot be interpreted as an integer
[2022-04-22 15:33:20,753 nonebot] INFO: Message -421822641 is ignored: Handled by Hoshino
```

**Comment by BlueDeer233** [comment]
[maimai_best_40.py line 296](https://github.com/Yuri-YuzuChaN/maimaiDX/blob/main/libraries/maimai_best_40.py#L296)
改成这样试试：`temp = temp.point(lambda p: int(p * 0.72))`
我们无法复现这个issue，不太敢直接修改repo
