### ISSUE TITLE
突然无法加载该插件

### ISSUE THREAD

**Issue by Akineru** [Yuri-YuzuChaN/maimaiDX#35]
之前是一直可以正常使用的 ，也没有对该插件文件和相关依赖进行任何改动。看到2022更新，尝试过重新下载并解压static文件也没用。查看日志报错如下：
ERROR: Failed to import "hoshino.modules.maimaiDX.maimai", error: Expecting ':' delimiter: line 4647 column 16 (char 108624)
ERROR: Expecting ':' delimiter: line 4647 column 16 (char 108624)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Downloads\HoshinoBot\hoshino\modules\maimaiDX\__init__.py", line 12, in <module>
    arcades: List[Dict] = json.load(open(arcades_json, 'r', encoding='utf-8'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 4647 column 16 (char 108624)

**Comment by Yuri-YuzuChaN** [comment]
目录有 `arcades.json` 文件吗

**Comment by Akineru** [comment]
有

**Comment by Yuri-YuzuChaN** [comment]
你重新下 `arcades.json` 试试，可能json对象不完整
