### ISSUE TITLE
启用插件后无法连接cqhttp

### ISSUE THREAD

**Issue by Renkousami** [Yuri-YuzuChaN/maimaiDX#54]
cqhttp端
[2023-03-15 19:33:54] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8222/ws
[2023-03-15 19:33:55] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8222/ws 时出现错误: dial tcp 127.0.0.1:8222: connectex: No connection could be made because the target machine actively refused it.

hoshinobot端
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\lifespan.py", line 59, in wait_for_startup
    await asyncio.wait_for(self.startup.wait(), timeout=self.config.startup_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 8, in <module>
    bot.run(use_reloader=False, loop=asyncio.get_event_loop())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\__init__.py", line 61, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 222, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\quart\app.py", line 1671, in run
    loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\__init__.py", line 41, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\run.py", line 81, in worker_serve
    await lifespan.wait_for_startup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\hypercorn\asyncio\lifespan.py", line 61, in wait_for_startup
    raise LifespanTimeoutError("startup") from error
hypercorn.utils.LifespanTimeoutError: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002454FD51A60>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Yuri-YuzuChaN** [comment]
这log没有关于插件的信息，自己看看hoshino哪里搞错了

**Comment by Renkousami** [comment]
找了半天没找到原因，用新的hoshinobot试了也不行，放弃了，还是谢谢柚子🥰

**Comment by Zya-MATO** [comment]
> 这log没有关于插件的信息，自己看看hoshino哪里搞错了

运行maimaibot插件需要安装retrying，安装retrying之前hoshinobot可以正常启动，但是maimaibot插件无法使用。安装retrying后maimaibot插件成功启动，但是hoshinobot出现了与题主一样的报错。

**Comment by Yuri-YuzuChaN** [comment]
> > 这log没有关于插件的信息，自己看看hoshino哪里搞错了
> 
> 运行maimaibot插件需要安装retrying，安装retrying之前hoshinobot可以正常启动，但是maimaibot插件无法使用。安装retrying后maimaibot插件成功启动，但是hoshinobot出现了与题主一样的报错。

现在的版本不需要retrying了

**Comment by Yuri-YuzuChaN** [comment]
> > > > 这log没有关于插件的信息，自己看看hoshino哪里搞错了
> > > 
> > > 
> > > 运行maimaibot插件需要安装retrying，安装retrying之前hoshinobot可以正常启动，但是maimaibot插件无法使用。安装retrying后maimaibot插件成功启动，但是hoshinobot出现了与题主一样的报错。
> > 
> > 
> > 现在的版本不需要retrying了
> 
> 换用新版本依旧报错。华为云Windows Server 2016 64位，Python 3.8.6

log看一下

**Comment by Yuri-YuzuChaN** [comment]
服务器能不能访问水鱼的查分器网站

**Comment by Yuri-YuzuChaN** [comment]
> > 服务器能不能访问水鱼的查分器网站
> 
> 可以访问

我这边重新装都是可以的，你的依赖是不是最新的

**Comment by Yuri-YuzuChaN** [comment]
实在不行就q联系我 806235364

**Comment by Yuri-YuzuChaN** [comment]
临时的解决方案，可能是因为服务器内部网络速度慢导致的

修改第 `9` 行代码
https://github.com/Yuri-YuzuChaN/maimaiDX/blob/475d9b0ca66534a786b96a2950d347abf65ba63b/maimai.py#L9
```python
from nonebot import NoneBot, on_startup, on_websocket_connect
```
修改第 `106` 和 `107` 行代码
https://github.com/Yuri-YuzuChaN/maimaiDX/blob/475d9b0ca66534a786b96a2950d347abf65ba63b/maimai.py#L106-L107
```python
@on_websocket_connect
async def get_music(event: CQEvent):
```

**Comment by Renkousami** [comment]
回来反馈下，我是windows servers环境的，关了clash之后可以正常使用插件了
