### ISSUE TITLE
API改动导致无法启动Bot

### ISSUE THREAD

**Issue by baka-chan402** [Yuri-YuzuChaN/maimaiDX#58]
```
[2023-04-15` 01:30:22,391 maimaiDX] INFO: 正在获取maimai所有曲目信息
Traceback (most recent call last):
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\quart\asgi.py", line 228, in __call__
    await self.app.startup()
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\quart\app.py", line 2149, in startup
    await func()
  File "C:\bot\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 89, in get_music
    await mai.get_music()
  File "C:\bot\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 295, in get_music
    self.total_list = await get_music_list()
  File "C:\bot\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 265, in get_music_list
    total_list[i].stats = stats[total_list[i].id]
KeyError: '8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\HoshinoBot\run.py", line 8, in <module>
    bot.run(use_reloader=False, loop=asyncio.get_event_loop())
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 61, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\__init__.py", line 222, in run    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\quart\app.py", line 1671, in run
    loop.run_until_complete(task)
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\hypercorn\asyncio\__init__.py", line 49, in serve
    await worker_serve(
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\hypercorn\asyncio\run.py", line 81, in worker_serve
    raise exception
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\hypercorn\asyncio\lifespan.py", line 43, in handle_lifespan
    await self.app(
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\hypercorn\app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\quart\app.py", line 2117, in __call__
    await self.asgi_app(scope, receive, send)
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\quart\app.py", line 2140, in asgi_app
    await asgi_handler(receive, send)
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\quart\asgi.py", line 230, in __call__
    await send({"type": "lifespan.startup.failed", "message": str(error)})
  File "C:\Users\sangh\AppData\Local\Programs\Python\Python39\lib\site-packages\hypercorn\asyncio\lifespan.py", line 101, in asgi_send
    raise LifespanFailureError("startup", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. ''8''
```

**Comment by Yuri-YuzuChaN** [comment]
已修复
