### ISSUE TITLE
更新了今天4.21的版本后报错

### ISSUE THREAD

**Issue by Kanade1551** [Yuri-YuzuChaN/maimaiDX#61]
大部分指令都报AttributeError: 'MaiMusic' object has no attribute 'total_list'
很怪（

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/89736912740ad3ffe27711803ed575fd0f26fc71

**Comment by Kanade1551** [comment]
好像还是不行 识别不到曲库的样子，b40指令跳这个
[2023-04-21 17:34:22,882 maimaiDX] ERROR: <class 'AttributeError'> occured when best_40 handling message 483188560.
[2023-04-21 17:34:22,882 maimaiDX] ERROR: 'MaiMusic' object has no attribute 'total_list'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 521, in best_40
    await bot.send(ev, await generate(payload), at_sender=True)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimai_best_50.py", line 449, in generate
    pic = await draw_best.draw()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimai_best_50.py", line 357, in draw
    self.whiledraw(self.sdBest, True, self.b50)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimai_best_50.py", line 290, in whiledraw
    dx = self._dxScore(info)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimai_best_50.py", line 189, in _dxScore
    notes: list[int] = mai.total_list.by_id(str(info.id)).charts[info.level]['notes']
AttributeError: 'MaiMusic' object has no attribute 'total_list'

**Comment by Yuri-YuzuChaN** [comment]
检查自己的bot在连接到gocq的时候获取数据正不正常
