### ISSUE TITLE
获取maimai曲目信息失败

### ISSUE THREAD

**Issue by CiaLion** [Yuri-YuzuChaN/maimaiDX#62]
`[2023-04-22 21:33:38,844 maimaiDX] INFO: 正在获取maimai所有曲目信息
[2023-04-22 21:33:44,626 maimaiDX] ERROR: Error: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 250, in get_music_list
    data = await obj_data.json()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client_reqrep.py", line 1099, in json
    await self.read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\streams.py", line 375, in read
    block = await self.readany()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\streams.py", line 397, in readany
    await self._wait("readany")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\streams.py", line 304, in _wait
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

[2023-04-22 21:33:44,626 maimaiDX] ERROR: maimaiDX曲目数据获取失败，请检查网络环境。已切换至本地暂存文件
[2023-04-22 21:33:50,844 maimaiDX] ERROR: Error: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 259, in get_music_list
    async with aiohttp.request('GET', 'https://www.diving-fish.com/api/maimaidxprober/chart_stats', timeout=aiohttp.ClientTimeout(total=5)) as obj_stats:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 1189, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 637, in _request
    break
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

[2023-04-22 21:33:50,844 maimaiDX] ERROR: maimaiDX数据获取错误，请检查网络环境。已切换至本地暂存文件
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<CQHttp._handle_event_with_response() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py:606> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 608, in _handle_event_with_response
    response = await self._handle_event(payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 601, in _handle_event
    filter(lambda r: r is not None, await
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 95, in get_music
    await mai.get_music()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 316, in get_music
    self.total_list = await get_music_list()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 271, in get_music_list
    async with aiofiles.open(os.path.join(static, 'chart_stats.json'), 'r', encoding='utf-8') as f:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiofiles\base.py", line 98, in __aenter__
    self._obj = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiofiles\threadpool\__init__.py", line 97, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\HoshinoBot\\hoshino\\modules\\maimaiDX\\static\\chart_stats.json'
`
不清楚是不是网络问题，前几天还能用来着

**Comment by BlueDeer233** [comment]
重启几次，并查看static文件夹内是否已生成chart_stats.json等本地备份文件

**Comment by Yuri-YuzuChaN** [comment]
尝试把这两行的超时时间改长 `total=30`
https://github.com/Yuri-YuzuChaN/maimaiDX/blob/7385f4ee8929657bfbb6cd719adfbc085890e1d9/libraries/maimaidx_music.py#L244
https://github.com/Yuri-YuzuChaN/maimaiDX/blob/7385f4ee8929657bfbb6cd719adfbc085890e1d9/libraries/maimaidx_music.py#L259

**Comment by CiaLion** [comment]
以上方法仍然无效，但在个人电脑上可以成功部署。在服务器上部署获取歌曲信息失败后跳出的提示类似 #61

**Comment by CiaLion** [comment]
> 以上方法仍然无效，但在个人电脑上可以成功部署。在服务器上部署获取歌曲信息失败后，对机器人发送指令跳出的提示类似 #61

重启服务器后，虽然仍旧无法更新歌曲信息，但是其他功能正常。不知道是哪里出问题了😓

**Comment by BlueDeer233** [comment]
把个人电脑上static文件夹的`music_data.json` `chart_stats.json` `all_alias.json` `arcades.json`复制到服务器对应位置再重启试试

**Comment by CiaLion** [comment]
> 把个人电脑上static文件夹的`music_data.json` `chart_stats.json` `all_alias.json` `arcades.json`复制到服务器对应位置再重启试试

这个能解决无法回复的问题，但仍旧无法解决更新乐曲失败的问题。可能是依赖或者确实是服务器网络问题。暂时先用从个人电脑上生成的备份文件复制到云服务器上的方法来解决了。
