### ISSUE TITLE
今天更新了2023的版本，重新装了更新后的文件 指令无法触发

### ISSUE THREAD

**Issue by Kanade1551** [Yuri-YuzuChaN/maimaiDX#69]
[2023-06-09 16:58:20,777 nonebot] INFO: Self: 2917410842, Message 1965609109 from 838256117@[群:337136720]: 'b50'
[2023-06-09 16:58:20,777 maimaiDX] INFO: Message 1965609109 triggered best_50.
[2023-06-09 16:58:22,798 maimaiDX] ERROR: <class 'FileNotFoundError'> occured when best_50 handling message 1965609109.
[2023-06-09 16:58:22,798 maimaiDX] ERROR: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\HoshinoBot\\hoshino\\modules\\maimaiDX\\static\\mai\\pic\\b40_score_basic.png'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 537, in best_50
    await bot.send(ev, await generate(payload), at_sender=True)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimai_best_50.py", line 376, in generate
    pic = await draw_best.draw()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimai_best_50.py", line 223, in draw
    basic = Image.open(os.path.join(self.maimai_dir, 'b40_score_basic.png'))
  File "C:\Users\Administrator\Desktop\maimai\lib\site-packages\PIL\Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\HoshinoBot\\hoshino\\modules\\maimaiDX\\static\\mai\\pic\\b40_score_basic.png'
[2023-06-09 16:58:22,814 nonebot] INFO: Message 1965609109 is ignored: Handled by Hoshino
不知道是什么情况 网络应该是没问题（

**Comment by Yuri-YuzuChaN** [comment]
静态资源全部更换，重新下载

**Comment by Kanade1551** [comment]
[2023-06-09 17:13:25,746 nonebot] INFO: Self: 2917410842, Message -206361069 from 838256117@[群:337136720]: 'b50'
[2023-06-09 17:13:25,749 maimaiDX] INFO: Message -206361069 triggered best_50.
[2023-06-09 17:13:26,362 maimaiDX] ERROR: <class 'FileNotFoundError'> occured when best_50 handling message -206361069.
[2023-06-09 17:13:26,362 maimaiDX] ERROR: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\HoshinoBot\\hoshino\\modules\\maimaiDX\\static\\mai\\pic\\b40_score_basic.png'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 537, in best_50
    await bot.send(ev, await generate(payload), at_sender=True)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimai_best_50.py", line 376, in generate
    pic = await draw_best.draw()
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimai_best_50.py", line 223, in draw
    basic = Image.open(os.path.join(self.maimai_dir, 'b40_score_basic.png'))
  File "C:\Users\Administrator\Desktop\maimai\lib\site-packages\PIL\Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\HoshinoBot\\hoshino\\modules\\maimaiDX\\static\\mai\\pic\\b40_score_basic.png'
[2023-06-09 17:13:26,362 nonebot] INFO: Message -206361069 is ignored: Handled by Hoshino
还是不行，下的静态资源应该是没问题的 最后一首是11509。方便的话能加企鹅我发下图片嘛（

**Comment by Yuri-YuzuChaN** [comment]
你确定你的目录是对的？
