### ISSUE TITLE
使用“曲师查歌”时报错

### ISSUE THREAD

**Issue by ZPluto0705** [Yuri-YuzuChaN/maimaiDX#76]
[2023-06-14 23:50:06,973 maimaiDX] ERROR: <class 'AttributeError'> occured when search_dx_song_artist handling message -1927921611.
[2023-06-14 23:50:06,973 maimaiDX] ERROR: 'Music' object has no attribute 'artist'
Traceback (most recent call last):
  File "/home/lighthouse/bot-linux/HoshinoBot/hoshino/msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "/home/lighthouse/bot-linux/HoshinoBot/hoshino/modules/maimaiDX/maimai.py", line 206, in search_dx_song_artist
    msg += f'No.{i + 1} {m.id}. {m.title} {m.artist}\n'
AttributeError: 'Music' object has no attribute 'artist'
[2023-06-14 23:50:06,976 nonebot] INFO: Message -1927921611 is ignored: Handled by Hoshino

**Comment by ZPluto0705** [comment]
收到，谢谢——！
