### ISSUE TITLE
更新至最新最热后，猜歌功能报错

### ISSUE THREAD

**Issue by KelsAstell** [Yuri-YuzuChaN/maimaiDX#79]
**如何复现**：当maimaiDX插件加载完成后，执行"猜歌"命令
**异常跟踪**：
`[2023-06-15 09:55:44,203 maimaiDX] INFO: 消息 1795304016 触发了 guess_music.
[2023-06-15 09:55:44,203 maimaiDX] ERROR: <class 'TypeError'> occured when guess_music handling message 1795304016.
[2023-06-15 09:55:44,203 maimaiDX] ERROR: __init__() takes exactly 1 positional argument (2 given)
Traceback (most recent call last):
  File "D:\iidxCore\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "D:\iidxCore\hoshino\service.py", line 223, in wrapper
    return await func(bot, event)
  File "D:\iidxCore\hoshino\modules\maimaiDX\maimai.py", line 339, in guess_music
    await mai.start()
  File "D:\iidxCore\hoshino\modules\maimaiDX\libraries\maimaidx_music.py", line 402, in start
    self.music = Music(random.choice(self.guess_data))
  File "pydantic\main.py", line 333, in pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (2 given)`

**期望的结果**：弃用pydantic，回滚为之前版本的猜歌代码，或进行Bug修正来使得该功能正常运行

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/8c4f2ac4ff23e16c05cccb0db5da08ee9b0f19e4

**Comment by KelsAstell** [comment]
感谢~
