### ISSUE TITLE
更新至最新最热后，上大分功能报错

### ISSUE THREAD

**Issue by SaigyoujiYusora** [Yuri-YuzuChaN/maimaiDX#85]
[2023-06-17 00:52:38,625 nonebot] INFO: Self: 1145810, Message -2048047635 from 114514@[群:1919810]: '我要在9上1分'
[2023-06-17 00:52:38,625 maimaiDX] INFO: Message -2048047635 triggered rise_score.
[2023-06-17 00:52:38,864 maimaiDX] ERROR: <class 'TypeError'> occured when rise_score handling message -2048047635.
[2023-06-17 00:52:38,864 maimaiDX] ERROR: 'Music' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Yusora\PycharmProjects\HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Yusora\PycharmProjects\HoshinoBot\hoshino\modules\maimaiDX\maimai.py", line 653, in rise_score
    data = await rise_score_data(payload, match, nickname)
  File "C:\Users\Yusora\PycharmProjects\HoshinoBot\hoshino\modules\maimaiDX\libraries\maimaidx_project.py", line 470, in rise_score_data
    if match.group(1) and music['level'][i] != match.group(1): continue
TypeError: 'Music' object is not subscriptable
[2023-06-17 00:52:38,865 nonebot] INFO: Message -2048047635 is ignored: Handled by Hoshino

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/8e2f5df8d44cda0879e6fd59edb4422605c725c0
