### ISSUE TITLE
使用"ginfo"时报错

### ISSUE THREAD

**Issue by ZPluto0705** [Yuri-YuzuChaN/maimaiDX#92]
[2023-07-06 20:56:10,405 maimaiDX] ERROR: <class 'OSError'> occured when globinfo handling message 1055926395.
[2023-07-06 20:56:10,408 maimaiDX] ERROR: ["ReferenceError: Can't find variable: echarts\n\n  file:////home/lighthouse/bot-linux/HoshinoBot/hoshino/modules/maimaiDX/static/temp_pie.html:12 in global code\nReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n"]
Traceback (most recent call last):
  File "/home/lighthouse/bot-linux/HoshinoBot/hoshino/msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "/home/lighthouse/bot-linux/HoshinoBot/hoshino/modules/maimaiDX/maimai.py", line 668, in globinfo
    await bot.send(ev, await music_global_data(music, level_index) + f'''
  File "/home/lighthouse/bot-linux/HoshinoBot/hoshino/modules/maimaiDX/libraries/maimaidx_project.py", line 385, in music_global_data
    await run_sync(make_snapshot)(snapshot, os.path.join(static, 'temp_pie.html'), os.path.join(static, 'temp_pie.png'), is_remove_html=False)
  File "/root/.cache/pypoetry/virtualenvs/hoshinobot-EJQ8clD8-py3.10/lib/python3.10/site-packages/quart/utils.py", line 67, in _wrapper
    result = await loop.run_in_executor(
  File "/usr/local/python3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.cache/pypoetry/virtualenvs/hoshinobot-EJQ8clD8-py3.10/lib/python3.10/site-packages/pyecharts/render/snapshot.py", line 45, in make_snapshot
    raise OSError(content_array)
OSError: ["ReferenceError: Can't find variable: echarts\n\n  file:////home/lighthouse/bot-linux/HoshinoBot/hoshino/modules/maimaiDX/static/temp_pie.html:12 in global code\nReferenceError: Can't find variable: echarts\n\n  undefined:1\nnull\n"]

**Comment by ZPluto0705** [comment]
刚才去下载了一份echarts.min.js现在可以了，谢谢——！
